-- AlterTable
ALTER TABLE "archives" ALTER COLUMN "title" SET DATA TYPE TEXT,
ALTER COLUMN "info" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "cases" ALTER COLUMN "title" SET DATA TYPE TEXT,
ALTER COLUMN "info" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "descriptions" ALTER COLUMN "title" SET DATA TYPE TEXT,
ALTER COLUMN "info" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "funds" ALTER COLUMN "title" SET DATA TYPE TEXT,
ALTER COLUMN "info" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "resources" ALTER COLUMN "title" SET DATA TYPE TEXT,
ALTER COLUMN "info" SET DATA TYPE TEXT;
